package com.kevin.pojo;

public class DataDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.dict_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.dict_parent_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer dictParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.dict_index
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer dictIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.dict_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dict.dict_value
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String dictValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.dict_id
     *
     * @return the value of data_dict.dict_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.dict_id
     *
     * @param dictId the value for data_dict.dict_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.dict_parent_id
     *
     * @return the value of data_dict.dict_parent_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getDictParentId() {
        return dictParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.dict_parent_id
     *
     * @param dictParentId the value for data_dict.dict_parent_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setDictParentId(Integer dictParentId) {
        this.dictParentId = dictParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.dict_index
     *
     * @return the value of data_dict.dict_index
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getDictIndex() {
        return dictIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.dict_index
     *
     * @param dictIndex the value for data_dict.dict_index
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setDictIndex(Integer dictIndex) {
        this.dictIndex = dictIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.dict_name
     *
     * @return the value of data_dict.dict_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.dict_name
     *
     * @param dictName the value for data_dict.dict_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dict.dict_value
     *
     * @return the value of data_dict.dict_value
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dict.dict_value
     *
     * @param dictValue the value for data_dict.dict_value
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }
}