package com.kevin.pojo;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_tel_num
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empTelNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_addr
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_email
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_id
     *
     * @return the value of employee.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_id
     *
     * @param empId the value for employee.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_no
     *
     * @return the value of employee.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_no
     *
     * @param empNo the value for employee.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpNo(String empNo) {
        this.empNo = empNo == null ? null : empNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_tel_num
     *
     * @return the value of employee.emp_tel_num
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpTelNum() {
        return empTelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_tel_num
     *
     * @param empTelNum the value for employee.emp_tel_num
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpTelNum(String empTelNum) {
        this.empTelNum = empTelNum == null ? null : empTelNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_addr
     *
     * @return the value of employee.emp_addr
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpAddr() {
        return empAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_addr
     *
     * @param empAddr the value for employee.emp_addr
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpAddr(String empAddr) {
        this.empAddr = empAddr == null ? null : empAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_email
     *
     * @return the value of employee.emp_email
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_email
     *
     * @param empEmail the value for employee.emp_email
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }
}