package com.kevin.pojo;

import java.math.BigDecimal;

public class Play {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_type_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer playTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_lang_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer playLangId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String playName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_introduction
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String playIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_image
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String playImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_length
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer playLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal playTicketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Short playStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_id
     *
     * @return the value of play.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_id
     *
     * @param playId the value for play.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_type_id
     *
     * @return the value of play.play_type_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getPlayTypeId() {
        return playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_type_id
     *
     * @param playTypeId the value for play.play_type_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayTypeId(Integer playTypeId) {
        this.playTypeId = playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_lang_id
     *
     * @return the value of play.play_lang_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getPlayLangId() {
        return playLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_lang_id
     *
     * @param playLangId the value for play.play_lang_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayLangId(Integer playLangId) {
        this.playLangId = playLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_name
     *
     * @return the value of play.play_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getPlayName() {
        return playName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_name
     *
     * @param playName the value for play.play_name
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayName(String playName) {
        this.playName = playName == null ? null : playName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_introduction
     *
     * @return the value of play.play_introduction
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getPlayIntroduction() {
        return playIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_introduction
     *
     * @param playIntroduction the value for play.play_introduction
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayIntroduction(String playIntroduction) {
        this.playIntroduction = playIntroduction == null ? null : playIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_image
     *
     * @return the value of play.play_image
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getPlayImage() {
        return playImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_image
     *
     * @param playImage the value for play.play_image
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayImage(String playImage) {
        this.playImage = playImage == null ? null : playImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_length
     *
     * @return the value of play.play_length
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getPlayLength() {
        return playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_length
     *
     * @param playLength the value for play.play_length
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayLength(Integer playLength) {
        this.playLength = playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_ticket_price
     *
     * @return the value of play.play_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getPlayTicketPrice() {
        return playTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_ticket_price
     *
     * @param playTicketPrice the value for play.play_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayTicketPrice(BigDecimal playTicketPrice) {
        this.playTicketPrice = playTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_status
     *
     * @return the value of play.play_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Short getPlayStatus() {
        return playStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_status
     *
     * @param playStatus the value for play.play_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayStatus(Short playStatus) {
        this.playStatus = playStatus;
    }
}