package com.kevin.pojo;

import java.math.BigDecimal;

public class SaleItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_item_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Long saleItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Long ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_item_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal saleItemPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_item_id
     *
     * @return the value of sale_item.sale_item_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Long getSaleItemId() {
        return saleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_item_id
     *
     * @param saleItemId the value for sale_item.sale_item_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleItemId(Long saleItemId) {
        this.saleItemId = saleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.ticket_id
     *
     * @return the value of sale_item.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.ticket_id
     *
     * @param ticketId the value for sale_item.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_ID
     *
     * @return the value of sale_item.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_ID
     *
     * @param saleId the value for sale_item.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_item_price
     *
     * @return the value of sale_item.sale_item_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getSaleItemPrice() {
        return saleItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_item_price
     *
     * @param saleItemPrice the value for sale_item.sale_item_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleItemPrice(BigDecimal saleItemPrice) {
        this.saleItemPrice = saleItemPrice;
    }
}