package com.kevin.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Date saleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_payment
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal salePayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_change
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal saleChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_type
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Short saleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Short saleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_ID
     *
     * @return the value of sale.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_ID
     *
     * @param saleId the value for sale.sale_ID
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.emp_id
     *
     * @return the value of sale.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.emp_id
     *
     * @param empId the value for sale.emp_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_time
     *
     * @return the value of sale.sale_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Date getSaleTime() {
        return saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_time
     *
     * @param saleTime the value for sale.sale_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleTime(Date saleTime) {
        this.saleTime = saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_payment
     *
     * @return the value of sale.sale_payment
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getSalePayment() {
        return salePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_payment
     *
     * @param salePayment the value for sale.sale_payment
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSalePayment(BigDecimal salePayment) {
        this.salePayment = salePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_change
     *
     * @return the value of sale.sale_change
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getSaleChange() {
        return saleChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_change
     *
     * @param saleChange the value for sale.sale_change
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleChange(BigDecimal saleChange) {
        this.saleChange = saleChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_type
     *
     * @return the value of sale.sale_type
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Short getSaleType() {
        return saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_type
     *
     * @param saleType the value for sale.sale_type
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleType(Short saleType) {
        this.saleType = saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_status
     *
     * @return the value of sale.sale_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Short getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_status
     *
     * @param saleStatus the value for sale.sale_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSaleStatus(Short saleStatus) {
        this.saleStatus = saleStatus;
    }
}