package com.kevin.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer schedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer studioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sched_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Date schedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sched_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal schedTicketPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sched_id
     *
     * @return the value of schedule.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSchedId() {
        return schedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sched_id
     *
     * @param schedId the value for schedule.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSchedId(Integer schedId) {
        this.schedId = schedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.studio_id
     *
     * @return the value of schedule.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.studio_id
     *
     * @param studioId the value for schedule.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.play_id
     *
     * @return the value of schedule.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.play_id
     *
     * @param playId the value for schedule.play_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sched_time
     *
     * @return the value of schedule.sched_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Date getSchedTime() {
        return schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sched_time
     *
     * @param schedTime the value for schedule.sched_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSchedTime(Date schedTime) {
        this.schedTime = schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sched_ticket_price
     *
     * @return the value of schedule.sched_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getSchedTicketPrice() {
        return schedTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sched_ticket_price
     *
     * @param schedTicketPrice the value for schedule.sched_ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSchedTicketPrice(BigDecimal schedTicketPrice) {
        this.schedTicketPrice = schedTicketPrice;
    }
}