package com.kevin.pojo;

public class Seat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer studioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_row
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer seatRow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_column
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer seatColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Short seatStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_id
     *
     * @return the value of seat.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_id
     *
     * @param seatId the value for seat.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.studio_id
     *
     * @return the value of seat.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.studio_id
     *
     * @param studioId the value for seat.studio_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_row
     *
     * @return the value of seat.seat_row
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSeatRow() {
        return seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_row
     *
     * @param seatRow the value for seat.seat_row
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSeatRow(Integer seatRow) {
        this.seatRow = seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_column
     *
     * @return the value of seat.seat_column
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSeatColumn() {
        return seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_column
     *
     * @param seatColumn the value for seat.seat_column
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSeatColumn(Integer seatColumn) {
        this.seatColumn = seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_status
     *
     * @return the value of seat.seat_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Short getSeatStatus() {
        return seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_status
     *
     * @param seatStatus the value for seat.seat_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSeatStatus(Short seatStatus) {
        this.seatStatus = seatStatus;
    }
}