package com.kevin.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Long ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Integer schedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private BigDecimal ticketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Short ticketStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_locked_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Date ticketLockedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_id
     *
     * @return the value of ticket.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_id
     *
     * @param ticketId the value for ticket.ticket_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat_id
     *
     * @return the value of ticket.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat_id
     *
     * @param seatId the value for ticket.seat_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.sched_id
     *
     * @return the value of ticket.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Integer getSchedId() {
        return schedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.sched_id
     *
     * @param schedId the value for ticket.sched_id
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setSchedId(Integer schedId) {
        this.schedId = schedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_price
     *
     * @return the value of ticket.ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public BigDecimal getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_price
     *
     * @param ticketPrice the value for ticket.ticket_price
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setTicketPrice(BigDecimal ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_status
     *
     * @return the value of ticket.ticket_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Short getTicketStatus() {
        return ticketStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_status
     *
     * @param ticketStatus the value for ticket.ticket_status
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setTicketStatus(Short ticketStatus) {
        this.ticketStatus = ticketStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_locked_time
     *
     * @return the value of ticket.ticket_locked_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Date getTicketLockedTime() {
        return ticketLockedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_locked_time
     *
     * @param ticketLockedTime the value for ticket.ticket_locked_time
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setTicketLockedTime(Date ticketLockedTime) {
        this.ticketLockedTime = ticketLockedTime;
    }
}