package com.kevin.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.emp_pass
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String empPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private Byte role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_path
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    private String headPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.emp_no
     *
     * @return the value of user.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.emp_no
     *
     * @param empNo the value for user.emp_no
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpNo(String empNo) {
        this.empNo = empNo == null ? null : empNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.emp_pass
     *
     * @return the value of user.emp_pass
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getEmpPass() {
        return empPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.emp_pass
     *
     * @param empPass the value for user.emp_pass
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setEmpPass(String empPass) {
        this.empPass = empPass == null ? null : empPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setRole(Byte role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_path
     *
     * @return the value of user.head_path
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public String getHeadPath() {
        return headPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_path
     *
     * @param headPath the value for user.head_path
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    public void setHeadPath(String headPath) {
        this.headPath = headPath == null ? null : headPath.trim();
    }
}