package com.kevin.dao;

import com.kevin.pojo.DataDict;
import com.kevin.pojo.DataDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    long countByExample(DataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByExample(DataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insert(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insertSelective(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    List<DataDict> selectByExample(DataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    DataDict selectByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") DataDict record, @Param("example") DataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExample(@Param("record") DataDict record, @Param("example") DataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKeySelective(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dict
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKey(DataDict record);
}