package com.kevin.dao;

import com.kevin.pojo.Play;
import com.kevin.pojo.PlayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    long countByExample(PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByExample(PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insert(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insertSelective(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    List<Play> selectByExample(PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    Play selectByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Play record, @Param("example") PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExample(@Param("record") Play record, @Param("example") PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKeySelective(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKey(Play record);
}