package com.kevin.dao;

import com.kevin.pojo.SaleItem;
import com.kevin.pojo.SaleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    long countByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByPrimaryKey(Long saleItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insert(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insertSelective(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    List<SaleItem> selectByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    SaleItem selectByPrimaryKey(Long saleItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleItem record, @Param("example") SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExample(@Param("record") SaleItem record, @Param("example") SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKeySelective(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKey(SaleItem record);
}