package com.kevin.dao;

import com.kevin.pojo.Sale;
import com.kevin.pojo.SaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    long countByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insertSelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    List<Sale> selectByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    Sale selectByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sale record, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExample(@Param("record") Sale record, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKeySelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKey(Sale record);
}