package com.kevin.dao;

import com.kevin.pojo.Studio;
import com.kevin.pojo.StudioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    long countByExample(StudioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByExample(StudioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int deleteByPrimaryKey(Integer studioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insert(Studio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int insertSelective(Studio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    List<Studio> selectByExample(StudioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    Studio selectByPrimaryKey(Integer studioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studio record, @Param("example") StudioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByExample(@Param("record") Studio record, @Param("example") StudioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKeySelective(Studio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbg.generated Mon Jun 04 11:43:39 CST 2018
     */
    int updateByPrimaryKey(Studio record);
}